version: '3.8'

services:
  generator:
    build:
      context: .
      args:
        WITH_WHISPER: ${WITH_WHISPER:-true}
    volumes:
      - ./assets:/app/assets
      - ./output:/app/output
    environment:
      - TRANSCRIPTION_ENABLED=${TRANSCRIPTION_ENABLED:-true}